apiVersion: batch/v1
kind: Job
metadata:
  name: list-databases
  namespace: task-manager
spec:
  template:
    spec:
      containers:
      - name: list-db
        image: postgres:13
        env:
        - name: PGPASSWORD
          value: "Shree@2025"
        command: ["psql"]
        args: 
        - "-h"
        - "34.122.121.162"
        - "-U"
        - "taskuser"
        - "-l"
      restartPolicy: Never
  backoffLimit: 3
