apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: task-manager
type: Opaque
data:
  username: dGFza3VzZXI=  # taskuser (base64 encoded)
  password: dGFza3Bhc3N3b3Jk  # taskpassword (base64 encoded)

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: task-manager
type: Opaque
data:
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # your-jwt-secret-key-change-in-production (base64 encoded)
