steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.prod'
      - '-t'
      - 'gcr.io/circular-hash-459513-q5/frontend:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/circular-hash-459513-q5/frontend:latest'
images:
  - 'gcr.io/circular-hash-459513-q5/frontend:latest'
