apiVersion: batch/v1
kind: Job
metadata:
  name: check-media-paths-job
  namespace: task-manager
spec:
  template:
    spec:
      containers:
      - name: postgres-client
        image: postgres:13
        command: ["psql"]
        args: 
          - "-h"
          - "34.122.121.162"
          - "-U"
          - "taskuser"
          - "-d"
          - "taskmanager"
          - "-c"
          - "SELECT id, filename, gcs_path FROM media WHERE id IN (9, 17, 19) ORDER BY id;"
        env:
        - name: PGPASSWORD
          value: "Shree@2025"
      restartPolicy: Never
  backoffLimit: 4
