apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: photo-albums
  labels:
    app: api-gateway
    version: v1
spec:
  replicas: 1  # Reduced for simplified deployment
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: gcr.io/circular-hash-459513-q5/api-gateway:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: node-env
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: auth-service-url
        - name: TASK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: album-service-url
        - name: MEDIA_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: media-service-url
        - name: FRONTEND_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: frontend-service-url
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: cors-origin
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: photo-albums
  labels:
    app: api-gateway
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: photo-albums
  labels:
    app: frontend
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer
