apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: task-manager
  labels:
    app: notification-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        version: v1
    spec:
      containers:
      - name: notification-service
        image: gcr.io/PROJECT_ID/notification-service:latest
        ports:
        - containerPort: 3004
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: redis-url
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: gcp-project-id
        - name: PUBSUB_TOPIC
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: pubsub-topic
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: host
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: port
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: user
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: password
        - name: SMTP_FROM
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: from
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: log-level
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/gcp/service-account.json"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: gcp-service-account
          mountPath: /etc/gcp
          readOnly: true
      volumes:
      - name: gcp-service-account
        secret:
          secretName: google-cloud-key

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: task-manager
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 3004
    protocol: TCP
    name: http
  type: ClusterIP
