apiVersion: apps/v1
kind: Deployment
metadata:
  name: album-service
  namespace: photo-albums
  labels:
    app: album-service
    version: v1
spec:
  replicas: 1  # Reduced for simplified deployment
  selector:
    matchLabels:
      app: album-service
  template:
    metadata:
      labels:
        app: album-service
        version: v1
    spec:
      containers:
      - name: album-service
        image: gcr.io/circular-hash-459513-q5/album-service:latest
        ports:
        - containerPort: 3002
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: node-env
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: auth-service-url
        - name: MEDIA_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: media-service-url
        - name: REDIS_URL
          value: "redis://redis.photo-albums.svc.cluster.local:6379"
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: cors-origin
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: album-service
  namespace: photo-albums
  labels:
    app: album-service
spec:
  selector:
    app: album-service
  ports:
  - port: 80
    targetPort: 3002
    name: http
  type: ClusterIP
